# Filterbank config
filterbank:
  n_filters: 64
  kernel_size: 4
  stride: 2
# Network config
masknet:
  in_chan: 64
  n_src: 2
  out_chan: 64
  bn_chan: 128
  hid_size: 128
  chunk_size: 200
  hop_size: 100
  n_repeats: 6
  mask_act: relu
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 200
  batch_size: 8
  num_workers: 8
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: data/wav16k/min/tr/
  valid_dir: data/wav16k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 16000
  mode: min
  segment: 2.0
# Additional config
use_pretrain:
  ckpt_path: /home/ymasuyama/tmu-sse/asteroid/egs/wham/DPRNN/exp/train_dprnn_16k_4sample_300/checkpoints/epoch=9-step=24800.ckpt
  model_path: # /home/ymasuyama/tmu-sse/asteroid/egs/wham/DPRNN/exp/train_dprnn_16k_4sample_300/best_model.pth
change_precision:
  precision: 16  # Default is 32
