# Filterbank config
filterbank:
  n_filters: 128
  kernel_size: 16
  stride: 8
# Network config
masknet:
  in_chan: 128
  n_src: 2
  out_chan: 128
  bn_chan: 256
  hid_size: 256
  chunk_size: 150
  hop_size: 75
  n_repeats: 6
  mask_act: relu
  bidirectional: true
  dropout: 0
# Training config
training:
  epochs: 200
  batch_size: 16
  num_workers: 8
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: !!float 1e-5
# Data config
data:
  train_dir: data/wav16k/min/tr/
  valid_dir: data/wav16k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 16000
  mode: min
  segment: 2.0
