## Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 16
  stride: 8
# Network config
masknet:
  num_blocks: 16
  mask_act: relu
  in_chan: 512
  bn_chan: 256
  upsampling_depth: 6
# Training config
training:
  epochs: 200
  batch_size: 16  # Single A6000
  num_workers: 8
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_clean
  nondefault_nsrc:
  sample_rate: 8000
  mode: min
  segment: 2.0
