# Filterbank config
filterbank:
  n_filters: 512
  kernel_size: 32
  stride: 16
# Network config
masknet:
  n_blocks: 8
  n_repeats: 3
  mask_act: relu
  bn_chan: 128
  skip_chan: 128
  hid_chan: 512
# Training config
training:
  epochs: 200
  batch_size: 16  # Single A6000
  num_workers: 8
  half_lr: yes
  early_stop: yes
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 0.
# Data config
data:
  task: sep_clean
  train_dir: data/wav16k/min/train-360
  valid_dir: data/wav16k/min/dev
  mode: min
  n_src: 2
  sample_rate: 16000
  segment: 2.5
